services:
  - type: web
    name: voice-llm-backend
    env: docker
    plan: free
    autoDeploy: true
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: "*"
    healthCheckPath: /

